defaults: &DEFAULTS
  gitolite_admin_path: /Users/alpkursun/temp/test_gitolite/gitolite-admin
  git_work_dir_path: /Users/alpkursun/temp/test_gitolite/work
  git_repo_prefix: 'git@skynet:'
  git_user_name: 'admin'
  git_user_email: 'git.admin@themepivot.com'

development:
  <<: *DEFAULTS

test:
  <<: *DEFAULTS

production:
  <<: *DEFAULTS