defaults: &DEFAULTS
  gitolite_admin_path: /Users/alpkursun/temp/test_gitolite/gitolite-admin
  git_work_dir_path: /Users/alpkursun/temp/test_gitolite/work
  git_repo_prefix: 'git@skynet:'
  git_user_name: 'admin'
  git_user_email: 'git.admin@themepivot.com'
  wordpress_unzip_path: /Users/alpkursun/temp/test_wordpress_unzip
  ftp_landing_path: /Users/alpkursun/temp/ftp_landing
  ftp_processed_path: /Users/alpkursun/temp/ftp_processed
  completed_project_path: /Users/alpkursun/temp/completed_proj
  marketplace_db_conn: 'mongodb://heroku:db0b1438e563f64f051101b2b393f0c1@staff.mongohq.com:10034/app2825221'
  marketplace_db_name: 'app2825221'
  wp_deploy_pivot_domain: 'http://localhost:8080'

development:
  <<: *DEFAULTS

test:
  <<: *DEFAULTS
  
preprod:
  gitolite_admin_path: /home/ubuntu/gitrepos/gitolite-admin
  git_work_dir_path: /var/www
  git_repo_prefix: 'git@pivot-node2:'
  git_user_name: 'ubuntu'
  git_user_email: 'admin+git@themepivot.com'
  wordpress_unzip_path: /home/ubuntu/wordpress
  ftp_landing_path: /home/ftp_shared/uploads
  completed_project_path: /home/ftp_shared/completed_proj
  ftp_processed_path: /home/ftp_shared/processed
  marketplace_db_conn: 'mongodb://heroku:db0b1438e563f64f051101b2b393f0c1@staff.mongohq.com:10034/app2825221'
  marketplace_db_name: 'app2825221'
  wp_deploy_pivot_domain: 'http://23.21.239.84:8080'

production:
  gitolite_admin_path: /home/ubuntu/gitrepos/gitolite-admin
  git_work_dir_path: /var/www
  git_repo_prefix: 'git@pivot-node1:'
  git_user_name: 'ubuntu'
  git_user_email: 'admin+git@themepivot.com'
  wordpress_unzip_path: /home/ubuntu/wordpress
  ftp_landing_path: /home/ftp_shared/uploads
  completed_project_path: /home/ftp_shared/completed_proj
  ftp_processed_path: /home/ftp_shared/processed
  marketplace_db_conn: 'mongodb://heroku:9eea2e25a2f6b27a9647b1a2e5475b1e@staff.mongohq.com:10027/app2414627'
  marketplace_db_name: 'app2414627'
  wp_deploy_pivot_domain: 'http://107.21.227.54:8080'
