defaults: &DEFAULTS
  job_root_path: /Users/alpkursun/temp
  gitolite_working_path: /Users/alpkursun/temp/test_gitolite/gitolite-admin
  gitolite_keydir_path: /Users/alpkursun/temp/test_gitolite/gitolite-admin/keydir
  gitolite_conf_file_path: /Users/alpkursun/temp/test_gitolite/gitolite-admin/conf/gitolite.conf
  gitolite_url_prefix: 'git@skynet:'

development:
  <<: *DEFAULTS

test:
  <<: *DEFAULTS

production:
  <<: *DEFAULTS