defaults: &DEFAULTS
  gitolite_admin_path: /tmp/test_gitolite/gitolite-admin
  git_work_dir_path: /tmp/test_gitolite/work
  git_repo_prefix: 'git@skynet:'
  git_user_name: 'admin'
  git_user_email: 'git.admin@themepivot.com'
  wordpress_unzip_path: /tmp/test_wordpress_unzip
  ftp_landing_path: /tmp/ftp_landing
  ftp_processed_path: /tmp/ftp_processed
  completed_project_path: /tmp/completed_proj
  marketplace_db_conn: 'mongodb://heroku:db0b1438e563f64f051101b2b393f0c1@staff.mongohq.com:10034/app2825221'
  marketplace_db_name: app2825221

development:
  <<: *DEFAULTS

test:
  <<: *DEFAULTS

production:
  gitolite_admin_path: /home/ubuntu/gitrepos/gitolite-admin
  git_work_dir_path: /var/www
  git_repo_prefix: 'git@pivot-node2:'
  git_user_name: 'ubuntu'
  git_user_email: 'admin+git@themepivot.com'
  wordpress_unzip_path: /home/ubuntu/wordpress
  ftp_landing_path: /home/ftp_shared/uploads
  completed_project_path: /home/ftp_shared/completed_proj
  ftp_processed_path: /home/ftp_shared/processed
  marketplace_db_conn: 'mongodb://heroku:db0b1438e563f64f051101b2b393f0c1@staff.mongohq.com:10034/app2825221'
  marketplace_db_name: app2825221
